// AUTO-GENERATED by `cortextos ecosystem`. Do NOT edit by hand.
// Re-run `cortextos ecosystem` to regenerate.
//
// Note: env vars use process.env.X || 'default' so PM2 picks up the value
// from the calling shell at startup time. This means `CTX_INSTANCE_ID=foo
// pm2 restart cortextos-daemon` switches instances without regenerating.
module.exports = {
  apps: [
    {
      name: 'cortextos-daemon',
      script: "/Users/loganbronstein/cortextos/dist/daemon.js",
      args: '--instance ' + (process.env.CTX_INSTANCE_ID || "default"),
      cwd: "/Users/loganbronstein/cortextos",
      env: {
        CTX_INSTANCE_ID: process.env.CTX_INSTANCE_ID || "default",
        CTX_ROOT: process.env.CTX_ROOT || "/Users/loganbronstein/.cortextos/default",
        CTX_FRAMEWORK_ROOT: "/Users/loganbronstein/cortextos",
        CTX_PROJECT_ROOT: "/Users/loganbronstein/cortextos",
        CTX_ORG: process.env.CTX_ORG || "cortex",
      },
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    },
  ],
};
