#!/usr/bin/env python3
"""
vault-lint.py — Karpathy Lint pass over Logan's Vault.

Scans for: broken wikilinks, orphan files (zero incoming links),
stale Compound notes (>30d unmodified), files missing source frontmatter.
Also surfaces DragonScale-style split candidates and boundary-first research
candidates without mutating the vault.

Output: Vault/Reports/cortextos-lint/YYYY-MM-DD.md
Run nightly. Findings are suggestions, not auto-fixed.
"""
from __future__ import annotations

import datetime as dt
import re
from pathlib import Path

VAULT = Path.home() / "Sale Advisor" / "Vault"
EXCLUDE = {".obsidian", ".claude-flow", "attachments", "Untitled"}

WIKILINK = re.compile(r"\[\[([^\]]+)\]\]")
SENSITIVE_TARGET = re.compile(r"(secret|token|password|credential|api[_ -]?key|private[_ -]?key|bearer|authorization|\.env)", re.I)
TODAY = dt.date.today().isoformat()


def safe_target(target: str) -> str:
    if SENSITIVE_TARGET.search(target):
        return "[redacted target]"
    return target


def main() -> None:
    md_files = [
        p for p in VAULT.rglob("*.md")
        if not any(part in EXCLUDE for part in p.parts)
    ]

    # Map every file's stem (lowercase) to its path for resolution
    stem_map: dict[str, Path] = {}
    for p in md_files:
        stem_map[p.stem.lower()] = p

    # 1. Find broken wikilinks
    broken_links: list[tuple[str, str]] = []
    incoming_count: dict[Path, int] = {p: 0 for p in md_files}

    for p in md_files:
        try:
            text = p.read_text(encoding="utf-8")
        except Exception:
            continue
        for m in WIKILINK.finditer(text):
            target = m.group(1).split("|")[0].split("#")[0].strip()
            target_lower = target.lower()
            target_stem = Path(target_lower).stem
            if target_stem in stem_map:
                target_path = stem_map[target_stem]
                if target_path != p:
                    incoming_count[target_path] += 1
            else:
                broken_links.append((p.name, target))

    # 2. Orphans: zero incoming links
    orphans: list[Path] = [
        p for p, count in incoming_count.items()
        if count == 0
        and "Daily Notes" not in p.parts  # daily notes are journal, not expected to be linked
        and "Templates" not in p.parts
    ]

    # 3. Stale Compound notes: under any Compound/ dir, mtime >30 days
    stale_compound: list[Path] = []
    cutoff = dt.datetime.now().timestamp() - 30 * 86400
    for p in md_files:
        if "Compound" in p.parts and p.stat().st_mtime < cutoff:
            stale_compound.append(p)

    # 4. Files missing frontmatter or deterministic IDs (Research/cortextos subtree only — agent-written files)
    missing_frontmatter: list[Path] = []
    missing_stable_id: list[Path] = []
    cortex_root = VAULT / "Research" / "cortextos"
    for p in md_files:
        try:
            if cortex_root in p.parents:
                head = p.read_text(encoding="utf-8")[:500]
                if not head.startswith("---"):
                    missing_frontmatter.append(p)
                elif not re.search(r"^id:\s*\S+", head, re.M):
                    missing_stable_id.append(p)
        except Exception:
            pass

    # 5. Semantic tiling candidates: large notes whose heading structure should be split or folded.
    tiling_candidates: list[tuple[Path, int, int]] = []
    for p in md_files:
        try:
            text = p.read_text(encoding="utf-8")
        except Exception:
            continue
        byte_count = len(text.encode("utf-8"))
        heading_count = len(re.findall(r"^#{2,6}\s+", text, re.M))
        if byte_count >= 25000 or heading_count >= 25:
            tiling_candidates.append((p, byte_count, heading_count))
    tiling_candidates.sort(key=lambda item: item[1], reverse=True)

    # 6. Boundary-first research candidates: repeated broken targets and isolated useful pages.
    broken_target_counts: dict[str, int] = {}
    for _, target in broken_links:
        broken_target_counts[target] = broken_target_counts.get(target, 0) + 1
    boundary_targets = sorted(
        broken_target_counts.items(),
        key=lambda item: (-item[1], item[0].lower()),
    )[:25]

    research_orphans = [
        p for p in orphans
        if ("Research" in p.parts or "Projects" in p.parts or "Rules" in p.parts or "Decisions" in p.parts)
    ][:25]

    # Write report
    out_dir = VAULT / "Reports" / "cortextos-lint"
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / f"{TODAY}.md"

    lines = [
        "---",
        f"date: {TODAY}",
        "type: lint-report",
        "agent: boss",
        "---",
        "",
        f"# Cortex Vault Lint Report — {TODAY}",
        "",
        "> Auto-generated by vault-lint.py. Karpathy Lint step. Run nightly. Findings are suggestions, not auto-fixed.",
        "",
        "## Summary",
        f"- Files scanned: {len(md_files)}",
        f"- Broken wikilinks: {len(broken_links)}",
        f"- Orphan files (zero incoming links, excluding Daily Notes): {len(orphans)}",
        f"- Stale Compound notes (>30 days unmodified): {len(stale_compound)}",
        f"- Files missing frontmatter: {len(missing_frontmatter)}",
        f"- Files missing deterministic id: {len(missing_stable_id)}",
        f"- Large notes to tile or fold: {len(tiling_candidates)}",
        f"- Boundary research targets: {len(boundary_targets) + len(research_orphans)}",
        "",
        "## Broken Wikilinks",
        "",
    ]

    if not broken_links:
        lines.append("(none)")
    else:
        for src, target in broken_links[:100]:
            lines.append(f"- `{src}` → `[[{safe_target(target)}]]`")
        if len(broken_links) > 100:
            lines.append(f"... and {len(broken_links) - 100} more.")

    lines += ["", "## Orphan Files", "", "These files have no incoming wikilinks. Consider linking them in or moving to Archive/.", ""]
    if not orphans:
        lines.append("(none)")
    else:
        for p in orphans[:100]:
            rel = p.relative_to(VAULT)
            lines.append(f"- [[{p.stem}]] (`{rel}`)")
        if len(orphans) > 100:
            lines.append(f"... and {len(orphans) - 100} more.")

    lines += ["", "## Stale Compound Notes", "", "These long-term notes have not been refreshed in >30 days. Review for currency.", ""]
    if not stale_compound:
        lines.append("(none)")
    else:
        for p in stale_compound:
            rel = p.relative_to(VAULT)
            lines.append(f"- `{rel}`")

    lines += ["", "## Missing Frontmatter (Research/cortextos/ files)", "", "Agent-written files should start with `---` YAML frontmatter for provenance.", ""]
    if not missing_frontmatter:
        lines.append("(none)")
    else:
        for p in missing_frontmatter[:50]:
            rel = p.relative_to(VAULT)
            lines.append(f"- `{rel}`")
        if len(missing_frontmatter) > 50:
            lines.append(f"... and {len(missing_frontmatter) - 50} more.")

    lines += ["", "## Missing Deterministic IDs (Research/cortextos/ files)", "", "Agent-written Cortex notes should include a stable `id:` in frontmatter so references survive renames and folds.", ""]
    if not missing_stable_id:
        lines.append("(none)")
    else:
        for p in missing_stable_id[:50]:
            rel = p.relative_to(VAULT)
            lines.append(f"- `{rel}`")
        if len(missing_stable_id) > 50:
            lines.append(f"... and {len(missing_stable_id) - 50} more.")

    lines += ["", "## Large Notes To Tile Or Fold", "", "DragonScale-style tiling candidates. Review these for split pages, fold rollups, or a better index.", ""]
    if not tiling_candidates:
        lines.append("(none)")
    else:
        for p, byte_count, heading_count in tiling_candidates[:50]:
            rel = p.relative_to(VAULT)
            lines.append(f"- `{rel}` — {byte_count // 1024} KB, {heading_count} headings")
        if len(tiling_candidates) > 50:
            lines.append(f"... and {len(tiling_candidates) - 50} more.")

    lines += ["", "## Boundary-First Research Candidates", "", "Repeated missing links and useful orphans show where the memory graph wants a new hub, source, or synthesis note.", ""]
    if not boundary_targets and not research_orphans:
        lines.append("(none)")
    else:
        for target, count in boundary_targets:
            lines.append(f"- Missing target `[[{safe_target(target)}]]` referenced {count} time(s)")
        for p in research_orphans:
            rel = p.relative_to(VAULT)
            lines.append(f"- Useful orphan candidate: [[{p.stem}]] (`{rel}`)")

    lines += ["", f"Lint pass complete: {TODAY}", ""]

    out.write_text("\n".join(lines), encoding="utf-8")

    print(f"Lint report: {out}")
    print(f"Files: {len(md_files)} | Broken: {len(broken_links)} | Orphans: {len(orphans)} | Stale: {len(stale_compound)} | NoFrontmatter: {len(missing_frontmatter)} | NoStableId: {len(missing_stable_id)} | Tile: {len(tiling_candidates)} | Boundary: {len(boundary_targets) + len(research_orphans)}")


if __name__ == "__main__":
    main()
