/**
 * Regression test for the silent-Telegram-disable trap (task_1776901473789_637).
 *
 * Before this fix, the .env template generated by `cortextos add-agent` only
 * included `BOT_TOKEN=` and `CHAT_ID=`. When a user filled in those two and
 * ran `cortextos start <agent>`, the daemon's security gate (agent-manager.ts:
 * "BOT_TOKEN is set but ALLOWED_USER is missing — refusing to enable Telegram")
 * silently disabled Telegram. The warning landed in ~/.pm2/logs/cortextos-
 * daemon-out.log where users never see it. The user thought their agent was
 * fully online but Telegram messages never arrived.
 *
 * The fix: include `ALLOWED_USER=` in the template plus a comment block
 * explaining why it's required. This test pins that contract so a future
 * refactor can't silently regress.
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { addAgentCommand } from '../../../src/cli/add-agent.js';

let projectRoot: string;
let savedCwd: string;

beforeEach(() => {
  projectRoot = mkdtempSync(join(tmpdir(), 'add-agent-env-test-'));
  savedCwd = process.cwd();
  process.chdir(projectRoot);

  // Point projectRoot resolution at the scratch dir so add-agent writes
  // INTO it (not the real repo). With no templates dir present, add-agent
  // falls through to createMinimalAgent — but the .env-template block we
  // care about runs unconditionally after the agent dir is created.
  process.env.CTX_FRAMEWORK_ROOT = projectRoot;
  delete process.env.CTX_PROJECT_ROOT;

  mkdirSync(join(projectRoot, 'orgs', 'testorg'), { recursive: true });
});

afterEach(() => {
  process.chdir(savedCwd);
  delete process.env.CTX_FRAMEWORK_ROOT;
  try { rmSync(projectRoot, { recursive: true, force: true }); } catch { /* ignore */ }
});

describe('add-agent .env template (silent-Telegram-disable bugfix)', () => {
  it('writes a .env with ALLOWED_USER placeholder + explanatory comment', async () => {
    // add-agent calls process.exit on success/failure for some paths; trap.
    const origExit = process.exit;
    let exitCode: number | undefined;
    (process as any).exit = (code?: number) => { exitCode = code; throw new Error(`__EXIT_${code}__`); };

    try {
      await addAgentCommand.parseAsync(
        ['node', 'cli', 'testagent', '--template', 'agent', '--org', 'testorg']
      ).catch(err => {
        // We expect the add-agent command to complete (it may or may not
        // call process.exit depending on path). Either way the .env should
        // be written by then.
        if (!String(err.message).startsWith('__EXIT_')) throw err;
      });
    } finally {
      (process as any).exit = origExit;
    }

    const envPath = join(projectRoot, 'orgs', 'testorg', 'agents', 'testagent', '.env');
    const content = readFileSync(envPath, 'utf-8');

    // Pin the three required fields.
    expect(content).toMatch(/^BOT_TOKEN=$/m);
    expect(content).toMatch(/^CHAT_ID=$/m);
    expect(content).toMatch(/^ALLOWED_USER=$/m);

    // Pin the explanation: future refactors should not strip the comment
    // block that explains WHY ALLOWED_USER is required.
    expect(content).toMatch(/ALLOWED_USER:\s+REQUIRED\s+when\s+BOT_TOKEN\s+is\s+set/);
    expect(content).toMatch(/numeric\s+Telegram\s+user\s+ID/);
    expect(content).toMatch(/@userinfobot/);

    // The exit code (if exit was called) should be 0 — successful add.
    if (exitCode !== undefined) expect(exitCode).toBe(0);
  });
});
